[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tpyside"
version = "1.0.0"
dependencies = [
    "pyside2"
]

[project.optional-dependencies]
tests = [
    "pytest",
]

